FROM ghcr.io/open-webui/open-webui:main

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    procps \
    psmisc \
    iproute2 \
    net-tools \
    vim-tiny \
    less \
    curl \
 && rm -rf /var/lib/apt/lists/*

